### ISSUE TITLE
Help wanted?

### ISSUE THREAD

**Issue by anderejd** [icefoxen/cargo-osha#1]
I was about to start a similar experiment when I found this repos 👍 

Have you thought about possible ways to do the dependency walk?
Would you like a PR?

**Comment by icefoxen** [comment]
I'd accept whatever help you wanted to make; this project was basically an experiment for me and I don't expect to continue it further.  If you want to make it a real project you can have commit access if you wish.  :-)

**Comment by anderejd** [comment]
Ok I'll probably experiment a bit tomorrow :) No commit access needed. I'll make a PR if I get anywhere useful.

**Comment by anderejd** [comment]
PR is up #7.

Closing this issue since I was just saying hi.
